import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base


class ChatMessage(Base):
    __tablename__ = "chat_messages"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("chat_sessions.id"), nullable=False, index=True
    )

    role: Mapped[str] = mapped_column(String(50), nullable=False)  # "user" | "assistant" | "system" | "tool"
    content: Mapped[str] = mapped_column(Text, nullable=False, default="")

    sources: Mapped[list[int] | None] = mapped_column(ARRAY(Integer), nullable=True)  # page numbers
    figures: Mapped[list[int] | None] = mapped_column(ARRAY(Integer), nullable=True)  # figure numbers
    tables: Mapped[list[int] | None] = mapped_column(ARRAY(Integer), nullable=True)   # table numbers

    # Optional Plotly chart JSON specification generated by visualization tool
    visualization_spec: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # Recorded tool calls if role == "assistant" or "tool"
    tool_calls: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )

    session = relationship("ChatSession", back_populates="messages")
