"""add content_blocks table

Revision ID: 4f29e91b0d25
Revises: b636b5235aaa
Create Date: 2026-07-18 16:04:54.187456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f29e91b0d25'
down_revision: Union[str, None] = 'b636b5235aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.Enum('TITLE', 'HEADING', 'TEXT', 'CAPTION', 'FIGURE', 'TABLE', 'EQUATION', 'REFERENCE', name='content_type'), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('bounding_box', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_blocks_content_type'), 'content_blocks', ['content_type'], unique=False)
    op.create_index(op.f('ix_content_blocks_page_number'), 'content_blocks', ['page_number'], unique=False)
    op.create_index(op.f('ix_content_blocks_paper_id'), 'content_blocks', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_blocks_paper_id'), table_name='content_blocks')
    op.drop_index(op.f('ix_content_blocks_page_number'), table_name='content_blocks')
    op.drop_index(op.f('ix_content_blocks_content_type'), table_name='content_blocks')
    op.drop_table('content_blocks')
    # ### end Alembic commands ###