"""add progress_percent to ingestion_jobs

Revision ID: b636b5235aaa
Revises: 487aef668679
Create Date: 2026-07-16 11:05:18.611276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b636b5235aaa'
down_revision: Union[str, None] = '487aef668679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_jobs', sa.Column('progress_percent', sa.Integer(), nullable=False,server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_jobs', 'progress_percent')
    # ### end Alembic commands ###