"""add progress_percent to ingestion_jobs

Revision ID: e124b7478c99
Revises: b44d3c76bae1
Create Date: 2026-07-09 09:52:47.317974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e124b7478c99'
down_revision: Union[str, None] = 'b44d3c76bae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###