import json
import logging
import uuid
from typing import Any

from sqlalchemy.orm import Session

from app.models.content_block import ContentBlock, ContentType
from app.services.qa import retrieve_relevant_content
from app.services.visualization.plotly_builder import build_plotly_spec_from_table

logger = logging.getLogger(__name__)


TOOL_DEFINITIONS = [
    {
        "type": "function",
        "function": {
            "name": "search_paper",
            "description": "Search the paper for relevant text passages, figure descriptions, or table summaries using semantic vector search.",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The search query or keywords to look for.",
                    }
                },
                "required": ["query"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "get_page",
            "description": "Retrieve all extracted content blocks (text, headings, figures, tables) on a specific page of the paper.",
            "parameters": {
                "type": "object",
                "properties": {
                    "page_number": {
                        "type": "integer",
                        "description": "1-indexed page number to fetch.",
                    }
                },
                "required": ["page_number"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "get_figure",
            "description": "Retrieve a specific figure's details including caption, visual description generated by VLM, and page number.",
            "parameters": {
                "type": "object",
                "properties": {
                    "figure_number": {
                        "type": "integer",
                        "description": "Figure number (e.g. 1 for Figure 1).",
                    }
                },
                "required": ["figure_number"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "get_table",
            "description": "Retrieve a specific table's details including caption, structured rows, summary, and page number.",
            "parameters": {
                "type": "object",
                "properties": {
                    "table_number": {
                        "type": "integer",
                        "description": "Table number (e.g. 2 for Table 2).",
                    }
                },
                "required": ["table_number"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "explain_equation",
            "description": "Retrieve an equation's content and its surrounding context/explanation from the paper.",
            "parameters": {
                "type": "object",
                "properties": {
                    "equation_identifier": {
                        "type": "string",
                        "description": "Equation number or identifier (e.g. '1', '6', 'equation 2').",
                    }
                },
                "required": ["equation_identifier"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "create_chart",
            "description": "Generate an interactive Plotly chart visualization from a specific table's structured data.",
            "parameters": {
                "type": "object",
                "properties": {
                    "table_number": {
                        "type": "integer",
                        "description": "The table number to plot.",
                    },
                    "chart_type": {
                        "type": "string",
                        "enum": ["bar", "line", "scatter"],
                        "description": "Type of chart to generate: bar, line, or scatter.",
                    },
                },
                "required": ["table_number"],
            },
        },
    },
]


def execute_tool_call(
    tool_name: str,
    arguments: dict[str, Any],
    paper_id: str,
    db: Session,
    context_accumulator: dict[str, Any],
) -> str:
    """Execute an agent tool call and update context accumulator safely."""
    if tool_name == "search_paper":
        query = arguments.get("query", "")
        items = retrieve_relevant_content(paper_id, query)
        for item in items:
            context_accumulator["sources"].add(item.page_number)
            if item.figure_number:
                context_accumulator["figures"].add(item.figure_number)
            if item.table_number:
                context_accumulator["tables"].add(item.table_number)

        formatted = []
        for i in items:
            formatted.append(f"[Page {i.page_number}] {i.text}")
        return "\n\n".join(formatted) if formatted else "No relevant items found."

    elif tool_name == "get_page":
        try:
            page_num = int(arguments.get("page_number", 1))
        except (ValueError, TypeError):
            page_num = 1

        context_accumulator["sources"].add(page_num)
        blocks = (
            db.query(ContentBlock)
            .filter(
                ContentBlock.paper_id == uuid.UUID(paper_id),
                ContentBlock.page_number == page_num,
            )
            .all()
        )
        if not blocks:
            return f"No content found for page {page_num}."

        lines = [f"Content on Page {page_num}:"]
        for b in blocks:
            lines.append(f"- [{b.content_type.value}] {b.content}")
        return "\n".join(lines)

    elif tool_name == "get_figure":
        try:
            fig_num = int(arguments.get("figure_number", 1))
        except (ValueError, TypeError):
            fig_num = 1

        context_accumulator["figures"].add(fig_num)
        blocks = (
            db.query(ContentBlock)
            .filter(
                ContentBlock.paper_id == uuid.UUID(paper_id),
                ContentBlock.content_type == ContentType.FIGURE,
            )
            .all()
        )
        target = None
        for b in blocks:
            if b.extra_data and b.extra_data.get("figure_number") == fig_num:
                target = b
                break
        if not target and blocks:
            target = blocks[0]

        if not target:
            return f"Figure {fig_num} not found in this paper."

        context_accumulator["sources"].add(target.page_number)
        caption = target.extra_data.get("caption", target.content) if target.extra_data else target.content
        description = target.extra_data.get("vlm_description", "No visual description available.") if target.extra_data else "N/A"
        return f"[Figure {fig_num} on Page {target.page_number}]\nCaption: {caption}\nDescription: {description}"

    elif tool_name == "get_table":
        try:
            tbl_num = int(arguments.get("table_number", 1))
        except (ValueError, TypeError):
            tbl_num = 1

        context_accumulator["tables"].add(tbl_num)
        blocks = (
            db.query(ContentBlock)
            .filter(
                ContentBlock.paper_id == uuid.UUID(paper_id),
                ContentBlock.content_type == ContentType.TABLE,
            )
            .all()
        )
        target = None
        for b in blocks:
            if b.extra_data and b.extra_data.get("table_number") == tbl_num:
                target = b
                break
        if not target and blocks:
            target = blocks[0]

        if not target:
            return f"Table {tbl_num} not found in this paper."

        context_accumulator["sources"].add(target.page_number)
        caption = target.extra_data.get("caption", "Table") if target.extra_data else "Table"
        summary = target.extra_data.get("vlm_summary", "") if target.extra_data else ""
        return f"[Table {tbl_num} on Page {target.page_number}]\nCaption: {caption}\nContent: {target.content}\nSummary: {summary}"

    elif tool_name == "explain_equation":
        eq_id = str(arguments.get("equation_identifier", "1"))
        blocks = (
            db.query(ContentBlock)
            .filter(
                ContentBlock.paper_id == uuid.UUID(paper_id),
                ContentBlock.content_type == ContentType.EQUATION,
            )
            .all()
        )
        if not blocks:
            return f"No equations found in this paper matching '{eq_id}'."

        target = blocks[0]
        context_accumulator["sources"].add(target.page_number)
        return f"[Equation on Page {target.page_number}]\nExpression: {target.content}"

    elif tool_name == "create_chart":
        try:
            tbl_num = int(arguments.get("table_number", 1))
        except (ValueError, TypeError):
            tbl_num = 1

        chart_type = str(arguments.get("chart_type", "bar"))
        context_accumulator["tables"].add(tbl_num)

        spec = build_plotly_spec_from_table(db, paper_id, tbl_num, chart_type)
        if spec:
            context_accumulator["visualization_spec"] = spec
            return f"Successfully generated a {chart_type} chart specification for Table {tbl_num}."
        else:
            return f"Could not extract numeric data from Table {tbl_num} to create a chart."

    return f"Unknown tool: {tool_name}"
